[package]
name = "energy-types"
version = "0.1.0"
authors = ["Luiz Rodrigues <luiz.rodrigues@unioeste.br>", "Kauan Carlos Campos <kauan.campos@unioeste.br"]
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
ink = { version = "5.0.2", default-features = false }

[features]
default = ["std"]
std = [
    "scale/std",
    "scale-info/std",
    "ink/std",
]
